import 'package:bloom_app/constants/colors/app_colors.dart';
import 'package:bloom_app/utils/fonts.dart';
import 'package:bloom_app/utils/gradient_mixin.dart';
import 'package:bloom_app/utils/spacing.dart';
import 'package:bloom_app/views/components/appbar_component.dart';
import 'package:bloom_app/views_models/settings/notifications_settings_view_model/notifications_settings_view_model.dart';
import 'package:flutter/material.dart';
import 'package:flutter_screenutil/flutter_screenutil.dart';
import 'package:get/get.dart';

class PrivacyPolicyView extends StatelessWidget with BLooMBackroundMixin {
  const PrivacyPolicyView({super.key});

  @override
  Widget build(BuildContext context) {
    return GetBuilder(
        init: NotificationSettingViewModel(),
        builder: (controller) {
          return Container(
              decoration: bLooMGradient(),
              child: Scaffold(
                appBar: const AppBarComponent(
                  title: 'Privacy Policy',
                ),
                body: SingleChildScrollView(
                  physics: const BouncingScrollPhysics(),
                  child: Column(
                      crossAxisAlignment: CrossAxisAlignment.start,
                      children: [
                        Text(
                          'Updated at January 1st, 2024',
                          style: Fonts.noto(
                              context, AppColors.black, 14, FontWeight.w600),
                        ),
                        VerticalSpacing(12.h),
                        Text(
                          '''BLooM (“we,” “our,” or “us”) is committed to protecting your privacy. This Privacy Policy explains how your personal information is collected, used, and disclosed by BLooM.

This Privacy Policy applies to our app, and its associated subdomains (collectively, our “Service”) alongside our application, BLooM. By accessing or using our Service, you signify that you have read, understood, and agree to our collection, storage, use, and disclosure of your personal information as described in this Privacy Policy and our Terms of Service.
''',
                          style: Fonts.noto(
                              context, AppColors.black, 12, FontWeight.w400),
                        ),
                        VerticalSpacing(12.h),
                        Text(
                          'Definitions and key terms',
                          style: Fonts.noto(
                              context, AppColors.black, 14, FontWeight.w600),
                        ),
                        VerticalSpacing(8.h),
                        Text(
                          '''To help explain things as clearly as possible in this Privacy Policy, every time any of these terms are referenced, are strictly defined as:

Cookie: small amount of data generated by a website and saved by your web browser. It is used to identify your browser, provide analytics, remember information about you such as your language preference or login information.
Company: when this policy mentions “Company,” “we,” “us,” or “our,” it refers to BLooM, that is responsible for your information under this Privacy Policy.
Country: where BLooM or the owners/founders of BLooM are based, in this case is United States
Customer: refers to the company, organization or person that signs up to use the BLooM Service to manage the relationships with your consumers or service users.
Device: any internet connected device such as a phone, tablet, computer or any other device that can be used to visit BLooM and use the services.
IP address: Every device connected to the Internet is assigned a number known as an Internet protocol (IP) address. These numbers are usually assigned in geographic blocks. An IP address can often be used to identify the location from which a device is connecting to the Internet.
Personnel: refers to those individuals who are employed by BLooM or are under contract to perform a service on behalf of one of the parties. ''',
                          style: Fonts.noto(
                              context, AppColors.black, 12, FontWeight.w400),
                        ),
                      ]).paddingSymmetric(horizontal: 16.w),
                ),
              ));
        });
  }
}
